title: Clebson Augusto Fonseca
author: whoisclebs
email: clebs.talks@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Bem-vindo ao WhoisClebs.Space, sua porta de entrada para o mundo 
  da tecnologia. Explore nosso blog e descubra histórias cativantes, 
  artigos esclarecedores e dicas práticas que unem a engenharia de 
  software ao desenvolvimento de produtos e soluções inovadoras. 
  Junte-se à nossa comunidade vibrante enquanto desvendamos os 
  segredos para o sucesso no cenário digital. 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
whoisclebs:
  name: Clebson Augusto
  tagline: Software engineer
  date_format: "%d de %b, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  profile_image: "assets/profile.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "pt-BR" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  navigation:
    - title: "Blog"
      url: "/"
    - title: "Sobre"
      url: "/sobre"
    - title: "Curriculo"
      url: "/curriculum"  
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: whoisclebs
    # github:  whoisclebs
    # linkedIn: in/whoisclebs
    #dribbble: jekyll
    #flickr:   jekyll
    # instagram: whoisclebs
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md

# Build settings
theme: whoisclebs

plugins:
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false
#  - jekyll-feed
